// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWAqL7bk3EGRC_fSDroNPF_XXDbneLw2I',
    appId: '1:938143383843:web:c85ee3ccfcee595b714c96',
    messagingSenderId: '938143383843',
    projectId: 'skystore-7dbc9',
    authDomain: 'skystore-7dbc9.firebaseapp.com',
    storageBucket: 'skystore-7dbc9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVY1f9KwIly8198th_kzcPJXnabVf5nSw',
    appId: '1:938143383843:android:636600bfd32f521a714c96',
    messagingSenderId: '938143383843',
    projectId: 'skystore-7dbc9',
    storageBucket: 'skystore-7dbc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtQ7Wubi1R131E5eDiCrT4b1Dg9B1tbU8',
    appId: '1:938143383843:ios:ba9a1e17a8cf8200714c96',
    messagingSenderId: '938143383843',
    projectId: 'skystore-7dbc9',
    storageBucket: 'skystore-7dbc9.appspot.com',
    androidClientId: '938143383843-lv9isbl1u38vujumolgs1ivv643qoumh.apps.googleusercontent.com',
    iosClientId: '938143383843-33cpj5f9etc8sr9dp1udu3pt922ui8gn.apps.googleusercontent.com',
    iosBundleId: 'com.example.skyStore',
  );

}